#21.01.20(16일차 Question Note)

##**_1번 질문_**
throws와 try ~ catch문의 적절한 사용때가 언제인가요?
비슷한 기능을 가지고 있다고 생각합니다.
throws는 메소드나 생성자를 수행할 때 발생하는 exception을
선언할때 사용된 키워드에 예외를 전가하는것이고, try ~ catch문은
예외발생할때 예외를 실행하게 되는데 둘다 비슷한 작업을 처리하는 듯한데
정확히 어떤 차이가 있는지를 모르겠습니다.


##**_2번 질문_**
SocketManager -
```java
public void send(Socket sock) throws IOException {
        System.out.print("숫자를 입력하세요: ");
        String str = scan.nextLine();

        out[ZERO] = sock.getOutputStream();
        out[ZERO].write(str.getBytes());
        }
```
해당 배열(클라이언트 또는 참가자)이 가지고 있는
가위바위보 값을 out[Zero]에 넣는게 맞나요??

> out[ZERO] = sock.getOutputStream();

##**_3번 질문_**
SocketManager -
서버쪽으로 입력은 정수로 받는데 스트링으로
변환하는 이유가 있나요?

> out[ZERO].write(str.getBytes());

##**_4번 질문_**
정기역량평가 4번문제를 풀다가
```java
private int numOne = 1;
    private int numTwo = 2;
    private int numThree = 3;
    private int gammerChioce;
    private int computerChoice;
    Scanner scan;
```
선언이 된상태인데 밑에서 int gammerChioce =  scan.nextInt(); 에서 gammerChioce =  scan.nextInt();
으로 변경했더니 값이 할당이 됬습니다. 왜그렇게 작동되는지 모르겠습니다.

```java
public int gammerChioce(){
        scan = new Scanner(System.in);
        System.out.print("1.가위 2.바위 3.보 중에서 하나를 선택하세요 : ");
        gammerChioce =  scan.nextInt();
        System.out.println("첫번째 gammerChioce 입니다 " + gammerChioce);

        return gammerChioce;
    }
```

